---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
    env: dev
  name: django
  namespace: api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: django
    env: dev
  type: ClusterIP
---
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django
    env: dev
  name: django
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      env: dev
  template:
    metadata:
      labels:
        app: django
        env: dev
    spec:
      containers:
      - image: eu.gcr.io/example/django
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /liveliness
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        name: django
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: django
    env: dev
  name: django
  namespace: api
spec:
  rules:
  - host: django.example.com
    http:
      paths:
      - backend:
          serviceName: django
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Namespace
metadata:
  name: app